server:
  port: 4000
  servlet:
    encoding:
      charset: utf-8

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/financial_db
#    db 세팅 후 포트 변경 예정
    username: postgres
    password: 1111

  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: classpath:/mybatis-config.xml
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl