name: Build and Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Gradle로 WAR 파일 빌드
      - name: Build WAR file
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      # 3. AWS CLI 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 4. WAR 파일을 S3에 업로드하고 Elastic Beanstalk에 배포
      - name: Deploy to Elastic Beanstalk
        run: |
          VERSION_LABEL="v-${{ github.run_id }}"
          aws s3 cp build/libs/financial_project-1.0.0.war s3://elasticbeanstalk-ap-northeast-2-235494805011/deployments/financial_project-${VERSION_LABEL}.war

          aws elasticbeanstalk create-application-version \
            --application-name "codechefproject" \
            --version-label "${VERSION_LABEL}" \
            --source-bundle S3Bucket="elasticbeanstalk-ap-northeast-2-235494805011",S3Key="deployments/financial_project-${VERSION_LABEL}.war"

          aws elasticbeanstalk update-environment \
            --environment-name "Codechefproject-env" \
            --version-label "${VERSION_LABEL}"
